version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sweater_backend
    ports:
      - "5432:5432"
  smtp_server:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    command: ["./bin/maildev"]
