version: "3.8"
services:
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sweater_backend
    ports:
      - "5432:5432"
  smtp_server:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    command: ["./bin/maildev"]
  backend:
    build:
      context: sweater-backend/
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db
      - smtp_server
  frontend:
    build:
      context: sweater-frontend/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend
